### ISSUE TITLE
Add "Legacy Stripe Checkout Modal" CSS Styles for Overlay Form

### ISSUE THREAD

**Issue by spencerfinnell** [wpsimplepay/wp-simple-pay-snippet-library#18]
It's not perfect, but for those who prefer the Stripe-branded legacy Stripe Checkout modal styling for overlay forms:

<img width="445" alt="Screen Shot 2019-09-15 at 4 30 16 PM" src="https://user-images.githubusercontent.com/491124/64927237-27126180-d7d6-11e9-9b23-c36028e46a65.png">

CSS

```css
.simpay-modal .simpay-modal__body {
	max-width: 300px;
	border-radius: 4px;
	box-shadow: 0 2px 3px rgba(0, 0, 0, 0.25);
	overflow: visible;
}

.simpay-modal .simpay-modal__content {
	padding-top: 45px;
	position: relative;
	background-color: #f5f5f7;
	position: relative;
	border-radius: 4px;
}

.simpay-modal__content:after {
	content: '';
	width: 100%;
	height: 95px;
	background: #e8e9eb;
	border-bottom: 1px solid #dbdcde;
	box-shadow: 0 1px 0 0 #fff;
	position: absolute;
	top: 0;
	left: 0;
	z-index: 0;
	border-top-left-radius: 4px;
	border-top-right-radius: 4px;
}

.simpay-modal .simpay-form-title, 
.simpay-modal .simpay-form-description {
	position: relative;
	z-index: 2;
}

.simpay-modal .simpay-form-title {
	margin-bottom: 5px;
	font-size: 18px;
}

.simpay-modal .simpay-form-description {
	font-size: 13px;
	font-weight: 400;
	color: #64636e;
}

.simpay-modal .simpay-checkout-form {
	margin-top: 40px;
}

.simpay-modal .simpay-form-control:not(:last-child) {
	margin-bottom: -9px;
}

.simpay-modal .simpay-form-control .simpay-card-wrap,
.simpay-modal .simpay-form-control input {
	border-radius: 0 !important;
}

.simpay-modal .simpay-form-control .StripeElement--focus,
.simpay-modal .simpay-form-control input:focus {
	border-color: #d1d1d1 !important;
}

.simpay-modal .simpay-form-control:first-child input {
	border-top-left-radius: 4px !important;
	border-top-right-radius: 4px !important;
	box-shadow: inset 0 1px 2px rgba(0, 0, 0, .05) !important;
}

.simpay-modal .simpay-form-control:last-child input {
	border-bottom-left-radius: 4px;
	border-bottom-right-radius: 4px;
	box-shadow: inset 0 1px 2px rgba(0, 0, 0, .05);
}

.simpay-modal .simpay-form-control .simpay-card-wrap {
	box-shadow: 0 1px 0 #fff;
	border-bottom-left-radius: 4px !important;
	border-bottom-right-radius: 4px !important;
}

.simpay-modal .simpay-form-control.simpay-checkout-btn-container {
	margin-top: 30px;
}

body .simpay-modal .simpay-form-control.simpay-checkout-btn-container .simpay-checkout-btn:not(.stripe-button-el) {
	text-shadow: 0 -1px 0 #009ae4;
	background: linear-gradient(to bottom, #00aeec, #0099e4);
	border-bottom: 1px solid #008cd8;
	box-shadow: 0 1px 2px rgba(0, 155, 229, 0.33);
}

body .simpay-modal .simpay-form-control.simpay-checkout-btn-container .simpay-checkout-btn:not(.stripe-button-el):hover,
body .simpay-modal .simpay-form-control.simpay-checkout-btn-container .simpay-checkout-btn:not(.stripe-button-el):active
{
	background: linear-gradient(to bottom, #0099e4, #0091d8);
	border-bottom: 1px solid #008cd8;
	box-shadow: 0 1px 2px rgba(0, 155, 229, 0.10);
}

.simpay-modal .simpay-modal-control-close {
	width: 18px;
	font-family: sans-serif;
	font-weight: bolder;
	color: #e7e8ea;
	font-size: 10px;
	z-index: 2;
	background: #c5c6c7;
	border-radius: 50%;
	box-shadow: 0 1px 0 rgba(255, 255, 255, 0.50), inset 0 1px 1px rgba(0, 0, 0, .10);
	height: 18px;
	text-align: center;
	padding: 0;
	line-height: 18px;
	text-shadow: 0 1px 0 rgba(0, 0, 0, .10);
	top: 10px;
	right: 10px;
}

.simpay-modal .simpay-modal-image {
	width: 70px;
	height: 70px;
	border: 3px solid #fff;
	position: absolute;
	top: -35px;
	left: 50%;
	margin-left: -35px;
	z-index: 2;
	border-radius: 50%;
	box-shadow: 0 1px 2px rgba(0, 0, 0, 0.20)
}

.simpay-modal .simpay-test-mode-badge-container {
	margin-top: 28px;
}
```

PHP

```php
add_action( 'simpay_form_12_before_payment_form', function() {
	echo '<img src="https://cdn.worldvectorlogo.com/logos/dribbble-icon-1.svg" alt="" class="simpay-modal-image" />';
}, 11 );
```
